[default]
DEBUG = true
FLASK_ADMIN_NAME = "Admin"
FLASK_ADMIN_TEMPLATE_MODE = "bootstrap3"
FLASK_ADMIN_SWATCH = 'cerulean'
TITLE = "ChessFish"
SECRET_KEY = "asdfasdfdfsa"
PASSWORD_SCHEMES = ['pbkdf2_sha512', 'md5_crypt']
EXTENSIONS = []